### PR TITLE
Tweaks to card searching algorithm

### PR DESCRIPTION
**Pull request by RusAD32**
1. Partial match is now checked not only in the beginning of the card name, but anywhere in the name
2. Added some code that should (hopefully) fetch a card even if the name is written with a typo. I explained how it is supposed to work in the code comments, but you may ask me more about it here or on reddit under /u/RusAD

### CODE REVIEW

**Comment by jrwhitehead** [comment]
There's an issue when a partial is matched. For example if I invoke the bot using {{guild}} the bot will find all cards with guild in but only comment the first one from the cards.json 'database'.

Also if someone comments {{a}} all cards are found with a in but the bot only returns the first card.

I think there needs to be some intelligence around this. Perhaps if more than 5 cards are found, post a comment including the first 5 cards and suggest that the user refines their search as too may cards were found?

**Comment by RusAD32** [comment]
Okay, I can rewrite the search function so that it returns multiple values, it's not that hard, actually, just give me a little bit of time. 
And after that, the bot can just print the first five matches and something like "Your query matched with too many cards to display at once. Could you be more specific please?"

**Comment by RusAD32** [comment]
It should work now. Plus I fixed some things along the way. If you need something else done, please let me know. Otherwise, I'll try writing a tool to fetch cards directly from legends-decks sometime in the near future

**Comment by jrwhitehead** [comment]
Awesome. I'll check it out and get back to you. Thanks so much for this.

**Comment by jrwhitehead** [comment]
Thanks again. Looks great.

**Pull request merged**
